### ISSUE TITLE
TypeError: argument 2 must be str, not dict

### ISSUE THREAD

**Issue by belfhi** [bloomberg/jupyterhub-kdcauthenticator#6]
Hello,
I'm trying to use Kerberos for the Authentication process of JupyterHub and found your Authenticator module.
I get the following error message:
    HTTPServerRequest(protocol='https', host='naf-belle-jhub.desy.de', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:131.169.214.92')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/conda/lib/python3.7/site-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/conda/lib/python3.7/types.py", line 277, in wrapped
        coro = func(*args, **kwargs)
      File "/root/jupyterhub-kdcauthenticator/kdcauthenticator/kdcauthenticator.py", line 148, in authenticate
        rc = kerberos.authGSSServerStep(state, data)
    TypeError: argument 2 must be str, not dict

When I searched the web, I found that pykerberos was needed instead of kerberos, but this seems to be the case on my system. 
Any ideas what could be wrong?
Cheers,
Johannes

**Comment by ebebpl** [comment]
I have the same error.  I followed the instructions given in: https://github.com/bloomberg/jupyterhub-kdcauthenticator . I have not seen any blogs with a successful outcome.

Did you find a solution for the error.
File "/opt/jupyter/jupyterhub-kdcauthenticator/kdcauthenticator/kdcauthenticator.py", line 148, in authenticate
        rc = kerberos.authGSSServerStep(state, data)
    TypeError: argument 2 must be str, not dict

**Comment by titan550** [comment]
I created a [pull request](https://github.com/bloomberg/jupyterhub-kdcauthenticator/pull/4) to fix this. Please follow this change. https://github.com/bloomberg/jupyterhub-kdcauthenticator/pull/4/commits/bda743c15c9cab9c63ecb635a90cc4ea6dc3b9da

**Comment by belfhi** [comment]
Thanks @titan550 I'll try this out but it seems like it's exactly what's causing the issue... But also it seems the maintainers aren't very active...
